### ISSUE TITLE
Remove master and slave wording

### ISSUE THREAD

**Issue by jviereck** [machines-in-motion/synchronizer#2]
The word usage "master" and "slave" is considered problematic and these days people use different terminologies. 

Please update the terminology in the repo.

**Comment by vincentberenz** [comment]
yes, now that you mention it, it seems totally obvious it is not best. I did the renaming, thanks for the notification

**Comment by jviereck** [comment]
Thanks for the quick fix @vincentberenz ! (The lead and follow scheme reminds me of ballroom, which is nice!)
